### PR TITLE
Move error message to I18N file

### LINKED ISSUE #11: Still maintained? + Localization support
Is this gem still maintained?

If so, it would be great if you can allow localization of the error message.

This block

https://github.com/HCLarsen/devise-uncommon_password/blob/cca8f40d05b4136fee5e053a71fd5bcffc38dd1e/lib/devise/uncommon_password/model.rb#L33-L37

Should probably just have something like:

```ruby
errors.add(:password, :common)
```

Which will just allow us to define the message in a localization file:

```ruby
# config/locales/activerecord.en.yml
en:
  activerecord: 
    errors:
      models:
        user:
          attributes:
            password:
              common: "must not be a commonly used password"
```

### PR DESCRIPTION
**Pull request by willianveiga**
Fix #11

### CODE REVIEW

**Comment by HCLarsen** [comment]
I'd much rather do this without adding an installer. Adding that extra step to use this gem isn't very user friendly. It should be possible to do this with a default value if no internationalization file is found.

**Comment by willianveiga** [comment]
I am not sure if it's possible to skip this installation step. The code didn't find the I18N file.

I'll try to add tests as soon as possible.

**Comment by HCLarsen** [comment]
Ideally, a user who isn't using I18N shouldn't require that file. That's why I'd like to avoid the installer. It's an extra step for people who may not even need what it does.

Also, keep in mind that Rails projects already have an I18N file in `config/locales/devise-uncommon-password.en.yml`. If someone were to add this gem to an existing project, your installer would overwrite that file with one that only serves this gem. 

The test failure could be the command you're using. Instead of `rake test`, try `bin/test`.

**Comment by willianveiga** [comment]
Actually, even if the user is not using I18N, the gem will require it to access the translations. I'm not sure if it's possible to do it without copying this file to the Rails app. Do you have any suggestion?

Which `Rails projects` ?

You are right. `bin/test` is the way to go. Sorry, I'm a rspec user :smiley:

**Comment by HCLarsen** [comment]
Maybe I didn't explain myself well there. If the developer isn't adding I18N to their app, then there is no need to access any translations. That's why adding this file would be an unneccesary step for anyone who's not internationalizing their app.

And no, I'm not familiar with adding I18N to a library, which is the main reason I haven't gotten around to adding this feature yet.

**Comment by willianveiga** [comment]
Yes, I  got it. But I cannot find a way to make it work without copying it. It will be a gem requirement, even if the user is not using I18N.

I've discovered other gems out there copying files to make it work. But I am not sure if this is the way to go.

Unfortunately I'm not familiar with adding I18N to a library either.

**Comment by HCLarsen** [comment]
Figured out how to do it without an installer on #19

**Pull request closed without merging**
